name: darahtanyoe_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_map: ^8.1.0
  timezone: ^0.9.2
  screenshot: ^3.0.0
  path_provider: ^2.0.15
  dotted_border: ^2.0.0
  lottie: ^2.6.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  share_plus: ^10.0.0
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.9
  flutter_layout_grid: ^2.0.7
  pinput: ^5.0.1
  google_fonts: ^6.1.0
  geolocator: ^13.0.3
  google_maps_flutter: ^2.11.0
  geocoding: ^3.0.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_aplikasi.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo_aplikasi.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo_aplikasi.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_aplikasi.png"

flutter:
  uses-material-design: true

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/logo/
    - assets/data/
    - assets/fonts/
    - .env
    - assets/animations/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
